### PR TITLE
fix(flap): set correct beg amount

### PR DESCRIPTION
**Pull request by e18r**
File flap.beg in the form (1 + percentage) * WAD instead of just percentage * WAD

### CODE REVIEW

**Comment by gbalabasquer** [comment]
The PR looks good, however it isn't the only percentage value with error. So far `mat` has the same problem.

**Comment by gbalabasquer** [comment]
Same for `flop` and `flip` `beg`.

**Comment by e18r** [comment]
@gbalabasquer working on it

**Comment by e18r** [comment]
@gbalabasquer I will create another pull request for these

**Comment by gbalabasquer** [comment]
Let's do everything here.

**Comment by e18r** [comment]
I also found `flop.beg` and `flap.beg` that need to be updated.

**Comment by gbalabasquer** [comment]
> I also found `flop.beg` and `flap.beg` that need to be updated.

Yeah I've mentioned them above ^^

**Comment by gbalabasquer** [comment]
`flop.pad` is also a rate in the form of `1.X`. It's correctly implemented now, however in a different way than the other one. We should standardize it.

**Comment by e18r** [comment]
I may be biased, but my way is better.

**Comment by brianmcmichael** [comment]
We're going to route around this in the exec this week. Let's fix it all up here and make sure everything is captured by the tests, we can deploy a new version next week sometime when gas is cheaper.

I'm with @gbalabasquer no judgment on whether your way is better or not. If you want to do it your way though we should update all of the other usages so that they are standardized.

**Comment by gbalabasquer** [comment]
The only advantage I see on adding up 1000 to the bps is that we need to use the unit just once.`beg` and `chop` are `wad` when `mat` is `ray`.
The other solution implies that we need to also make sure the addition is using the correct unit a part of the correct div function.

**Comment by e18r** [comment]
> So far `mat` has the same problem.

`mat` is different. It is correctly specified in the form pct * RAD, instead of (1 + pct) * RAD. It's just a pretty big percentage. Also, the code makes sure it doesn't surpass 1,000 %.

So I think it's good as it is.

**Comment by e18r** [comment]
@gbalabasquer @brianmcmichael ready for review

**Comment by gbalabasquer** [comment]
`mat` needs to be in the form of `1.x * RAY` .

**Review by brianmcmichael — APPROVED** [review]
Going to merge this for now to progress with some other work. We should have these tested in a new PR I think.

**Pull request merged**
