### PR TITLE
File directly to correct division precision loss

### PR DESCRIPTION
**Pull request by brianmcmichael**
Increase and decrease functions were dividing `Line` by `RAD` which might result in some precision loss of the Global Line. This removes the division and files directly against the vat.

### CODE REVIEW

**Review by e18r — APPROVED** [review]
LGTM

**Review by hexonaut — APPROVED** [review]
LGTM 👍

**Comment by hexonaut** [comment]
Actually, you probably want to make this same change for `increaseIlkDebtCeiling` and `decreaseIlkDebtCeiling` as the same issue applies there.

**Review by e18r — APPROVED** [review]

**Review by gbalabasquer — APPROVED** [review]
LGTM, only thing I can say is IMO doing `_amount < MathLib.WAD` is a bit confusing. I know we are trying to limit the size of amount considering that needs to be multiplied by `* RAD`, so this way we can catch up users that by mistake would be sending the full number. However the unit `WAD` IMO is confusing as has nothing to do with debt ceilings. If we want to block users that are sending the full number, I think it would be better represented with:
```
_amount < MathLib.RAD
```

**Comment by e18r** [comment]
I agree it can be confusing. However, `amount < RAD` doesn't prevent people from sending `wad`s, which is probably a common mistake. Your second example works better, but it's a bit arbitrary. In order to prevent the confusion, we can encapsulate the current WAD check into a function:

    require(isRegularAmount(_amount))

Maybe we should also come up with a name for this kind of amount: how about `lay`?

**Comment by gbalabasquer** [comment]
Right, the `RAD` solution doesn't prevent sending `WAD` which is also a bit arbitrary as it is still a huge number.
The `100 * BILLION` is arbitrary but IMO has more to do with a common sense max debt ceiling. Today we are in the 2-3 BILLION range, so we aren't too far from that limit but with enough room to grow for a couple of years at least.

**Comment by brianmcmichael** [comment]
All of the `require` statements here are merely precision checks. If we want to start enforcing actual limits on values it should be part of a separate PR and encompass the entire library.

**Comment by gbalabasquer** [comment]
Fair enough, I just wondering if doing `_amount < MathLib.WAD` will get users confused about the final unit of the debt ceilings.
Maybe with a comment that says something "we are expecting a regular number (not WAD, RAY or RAD)". But we can discuss that in another PR.

**Pull request merged**
